version: "3.7"
services:
  # 서버 설정
  backend:
    image: 645380415845.dkr.ecr.ap-northeast-2.amazonaws.com/studykit:latest
    container_name: backend
    network_mode: "host"

  # nginx 설정
  nginx:
    depends_on:
      - backend
    network_mode: "host"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx