version: '3'
services:
  prod:
    container_name: prod
    image: 645380415845.dkr.ecr.ap-northeast-2.amazonaws.com/studykit:latest
    ports:
      - "5000:5000"
  dev:
    container_name: dev
    image: 645380415845.dkr.ecr.ap-northeast-2.amazonaws.com/dev:latest
    ports:
      - "5050:5050"
  nginx:
    container_name: nginx
    depends_on:
      - prod
      - dev
    image: 645380415845.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile